name: gym_sof
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.2.0
  firebase_core: ^2.27.2
  firebase_storage: 
  hive: 
  hive_flutter: 
  image_picker: ^1.0.7 
  permission_handler:
  get:
  intl:
  flutter_screenutil:
  cloud_firestore: ^4.15.10
  connectivity_plus: ^6.0.1
  path: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: 
  build_runner: 
flutter:
  uses-material-design: true
  assets:
    - assets/