name: gym_sof
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress:
  hive: 
  hive_flutter: 
  image_picker: 
  permission_handler:
  get:
  intl:
  flutter_screenutil:
  animations: ^2.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: 
  build_runner: 
flutter:
  uses-material-design: true
  assets:
    - assets/